package com.ideas2it.employeeManagementSystem.constants;

/**
 * To hold the constant values
 * 
 * @author TamilarasiShanmugasundaram created 15-03-2021
 */
public class Constants {
	public static final int ZERO = 0;
	public static final int MINUS_ONE = -1;
	public static final String OPERATION = "operation";
	public static final String MESSAGE = "Message";
	public static final String DISPLAY_ALL_EMPLOYEE = "displayAllEmployee";
	public static final String DISPLAY_SINGLE_EMPLOYEE = "displaySingleEmployee";
	public static final String RETRIEVE = "Retrieve";
	public static final String CREATE = "create";
	public static final String UPDATE_EMPLOYEE = "UpdateEmployee";
	public static final String UPDATE = "update";
	public static final String ASSIGN_EMPLOYEE = "AssignEmployee";
	public static final String ASSIGN_PROJECT = "AssignProject"; 
	public static final String UNASSIGN_EMPLOYEE = "UnassignEmployee";
	public static final String UPDATE_ALL = "UpdateAll"; 
	public static final String UPDATE_NAME = "UpdateName";
	public static final String UPDATE_PHONENUMBER = "UpdatePhoneNumber";
	public static final String UPDATE_PROJECT = "UpdateProject";
	public static final String UPDATE_PERMANENT_ADDRESS = "UpdatePermanentAddress";
	public static final String UPDATE_TEMPORARY_ADDRESS = "UpdateTemporaryAddress";
	public static final String DELETE = "delete";	
	public static final String RETRIEVE_DETAILS = "retrieve";
	public static final String UNASSIGN_PROJECT = "UnassignProject";
	public static final String DISPLAY_ALL_PROJECT = "DisplayAllProject";
	public static final String DISPLAY_SINGLE_PROJECT = "displaySingleProject";
	public static final String DISPLAY = "1. Employee 2. Project 3.Exit";
	public static final String EMPLOYEE_OPTION_BANNER = "1. Create 2. Update 3. Delete 4. Display 5.Assign Project 6. Retrieve Employee 7.Unassign Project 8. Exit";
	public static final String PROJECT_OPTION_BANNER = "1. Create 2. Update 3. Delete 4. Display 5.Assign employee 6. Retrieve Project 7.Unassign Employee 8.Exit";
	public static final String ENTER_CHOICE = "Enter the option";
	public static final String ENTER_VALID_CHOICE = "Enter valid option";
	public static final String ENTER_DOORNUMBER = "Enter doorNumber";
	public static final String ENTER_STREET_NUMBER = "Enter streetNumber --Eg: 1--";
	public static final String ENTER_CITY = "Enter city";
	public static final String ENTER_DISTRICT = "Enter district";
	public static final String ENTER_STATE = "Enter state";
	public static final String ENTER_COUNTRY = "Enter country";
	public static final String ENTER_PINCODE = "Enter pincode";
	public static final String ENTER_NAME = "Enter name";
	public static final String ENTER_PHONENUMBER = "Enter Phone number";
	public static final String ENTER_EMAILID = "Enter emailId ";
	public static final String ENTER_DOB = "Enter DOB -- yyyy-mm-dd-- ";
	public static final String ENTER_DOJ = "Enter DOJ -- yyyy-mm-dd-- ";
	public static final String ENTER_TITLE = "Enter title";
	public static final String ENTER_START_DATE = "Enter start date --yyyy-mm-dd--";
	public static final String ENTER_END_DATE = "Enter estimate end date -- yyyy-mm-dd--";
	public static final String ENTER_STATUS = "Enter project status";
	public static final String ENTER_CLIENT = "Enter client";
	public static final String ENTER_BUDGET = "Enter budget";
	public static final String FALSE = "false";
	public static final String TRUE = "true";
	public static final String ENTER_PERMANENT_ADDRESS = "***Enter your permanent address***";
	public static final String ENTER_VALID_NUMBER = "Enter valid input";
	public static final String ENTER_ANOTHER_ADDRESS = "If you want to enter another address";
	public static final String YES_NO = "1. Yes 2. No";
	public static final String ENTER_EMPLOYEE_ID = "Enter the employee id";
	public static final String ENTER_PROJECT_ID = "Enter the project id";
	public static final String ADD_SUCCESS = "Added successfully";
	public static final String ADD_FAILURE = "Not added";
	public static final String DELETE_SUCCESS = "Deleted successfully";
	public static final String GET_DELETED_EMPLOYEE_SUCCESS = "Get deleted employee successfully";
	public static final String GET_DELETED_PROJECT_SUCCESS = "Get deleted project successfully";
	public static final String GET_EMPLOYEE_BY_ID_SUCCESS = "Get employee details by id successfully ";
	public static final String GET_PROJECT_BY_ID_SUCCESS = "Get project details by id successfully ";
	public static final String GET_ALL_EMPLOYEE_SUCCESS = "Get all employee successfully ";
	public static final String GET_ALL_PROJECT_SUCCESS = "Get all project successfully ";
	public static final String GET_TEMPORARY_ADDRESS = "Get temprary address by id successfully";
	public static final String ASSIGN_SUCCESS = "Assigned successfully";
	public static final String ASSIGN_FAILURE = "Not assigned";
	public static final String UNASSIGN_SUCCESS = "Unassigned successfully";
	public static final String EMPLOYEE_NOT_ASSIGN = "Employee is not assigned to Project";
	public static final String PROJECT_NOT_ASSIGN =	"Project is not assigned to employee";
	public static final String ALREADY_ASSIGN = "project and employee is already assigned";
	public static final String UNASSIGN_FAILURE = "Not unassigned";
	public static final String DELETE_FAILURE = "Not deleted";
	public static final String EMPLOYEE_NOT_EXIST = "Employee does not exist";
	public static final String COMPLETE_SUCCESS = "Operation completed successfully";
	public static final String PROJECT_NOT_EXIST = "Project does not exist";
	public static final String RETRIEVE_SUCCESS = "Retrieved successfully";
	public static final String RETRIEVE_FAILURE = "Not retrieved";
	public static final String NO_EMPLOYEES = "There is no employees";
	public static final String ENTER_FIELD_FOR_UPDATE = "Enter the field you want to update";
	public static final String FIELD_FOR_UPDATE = "1.Name 2.Address 3.EmailId 4.Phonenumber";
	public static final String FIELD_FOR_PROJECT_UPDATE = "1.Title 2.Estimate end date 3.Budget 4.Client 5.Status";
	public static final String FIELD_FOR_ADDRESS_UPDATE = "1.Permanent address 2. Temporary address";
	public static final String ADDRESS = "Address : ";
	public static final String UPDATE_SUCCESS = "Updated successfully";
	public static final String UPDATE_FAILURE = "Not Updated";
	public static final String ENTER_ADDRESS_NUMBER = "Enter your address number you want to update";
	public static final String NO_PERMANENT_ADDRESS = "Employee does not have temporary address";
	public static final String FIELDS_FOR_DISPLAY_EMPLOYEE = "1. All employee details  2.single employee detail";
	public static final String FIELDS_FOR_DISPLAY_PROJECT = "1. All project details  2.single project detail";
	public static final String NAME_REGEX = "^[a-zA-Z\\s]+";
	public static final String EMAIL_REGEX = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$";
	public static final String DATE_REGEX = "^[12]\\d{3}-(0[1-9]|1[0-2])" + "-(0[1-9]|[12]\\d|3[01])$";
	public static final String PHONENUMBER_REGEX = "(0/91)?[7-9][0-9]{9}";
	public static final String EMPLOYEE_SELECT_QUERY = "from Employee where is_delete = false";
	public static final String PROJECT_SELECT_QUERY = "from Project where is_delete = false";
	public static final String GET_PERMANENT_ADDRESS_QUERY = "from Address where employee_id = :id AND is_permanent = true";
	public static final String GET_TEMPRARORY_ADDRESS_QUERY = "from Address where employee_id = :id AND is_permanent = false";
	
	public static final String GET_DELETED_EMPLOYEE_BY_ID_QUERY = "from Employee where employee_id = :id AND is_delete = true";
	public static final String GET_DELETED_PROJECT_BY_ID_QUERY = "from Project where project_id = :id AND is_delete = true";
	public static final String GET_DELETED_EMPLOYEE_QUERY = "from Employee where is_delete = true";
	public static final String GET_DELETED_PROJECT_QUERY = "from Project where is_delete = true";
	public static final String EMPLOYEE_EXIST_QUERY = "from Employee where employee_id = :id AND is_delete = false";
	public static final String PROJECT_EXIST_QUERY = "from Project where project_id = :id AND is_delete = false";
	public static final String EMAIL_ID_EXIST_QUERY = "from Employee where email_id = :emailId";
	public static final String PHONENUMBER_EXIST_QUERY = "from Employee where phone_number = :phoneNumber";
	public static final String INVALID_TIME_INTERVAL = "****Invalid time interval for project completion****";
	public static final String EMPLOYEE_MANAGEMENT_EXCEPTION = "****Something went wrong !! Contact Admin !!****";
	public static final String PHONENUMBER_EXIST = "Phone number already exist";
	public static final String EMAIL_EXIST = "Email id already exist";
	public static final String EMAILID_NOT_VALID = "email id is not valid";
	public static final String PHONENUMBER_NOT_VALID = "Phone number is not valid";
	public static final String ERROR = "Error occured : ";
	public static final String EXCEPTION = "Exception";
	public static final String BOOLEAN = "Boolean";
	public static final String DELETED_EMPLOYEES = "deletedEmployees";
	public static final String DELETED_PROJECTS ="deletedProjects";
	public static final String EMPLOYEE = "employee";
	public static final String EMPLOYEES = "Employees";
	public static final String PROJECT = "project";
	public static final String PROJECTS = "Projects";
	public static final String EMPLOYEE_ID = 	"employeeId";
	public static final String PROJECT_ID = "projectId";
	public static final String ID = "id";
	public static final String DOB = "dob";
	public static final String DOJ = "doj";
	public static final String NAME = "name";
	public static final String EMAIL_ID = "emailId";   
	public static final String PHONENUMBER = "phonenumber";
	public static final String PHONENUMBER_DB = "phoneNumber";
	public static final String PERMANENT = "permanent";
	public static final String TEMPORARY = "temporary";
	public static final String DOORNUMBER = "DoorNumber";
	public static final String STREETNUMBER = "StreetNumber";
	public static final String CITY = "City";
	public static final String DISTRICT = "District";
	public static final String STATE = "State";
	public static final String COUNTRY = "Country";
	public static final String PINCODE = "Pincode";
	public static final String TITLE = "title";
	public static final String STATUS = "status";
	public static final String CLIENT = "client";
	public static final String BUDGET = "budget";
	public static final String START_DATE = "startDate";
	public static final String END_DATE = "estimatedEndDate";
	public static final String EMPLOYEE_SERVICE_IMPL = "EmployeeServiceImpl";
	public static final String EMPLOYEE_DAO_IMPL = 	"EmployeeDaoImpl";
	public static final String CONFIGURATION_FILE_PATH = "resources/properties/hibernate.cfg.xml";
}
